### ISSUE TITLE
Roadmap: 2.x 

### ISSUE THREAD

**Issue by fsmanuel** [funkensturm/ember-local-storage#335]
The main goals for upcoming 2.x releases are:

- [ ] Update the documentation to include examples for native classes
- [ ] Remove deprecations
- [ ] Make it Embroider ready
- [ ] Investigate/research opportunities native classes and tracked properties may enable
- [ ] Release and Changelog. Use [release-it-lerna-changelog
](https://github.com/rwjblue/release-it-lerna-changelog)

Join the discussion: https://github.com/funkensturm/ember-local-storage/discussions/334
